# Generated by Django 4.0.4 on 2022-07-22 09:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='user_profile',
            new_name='UserProfileInfo',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_Pic',
            new_name='profile_pic',
        ),
    ]
